# Generated by Django 5.2.1 on 2025-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=15, unique=True)),
                ('passUsuario', models.CharField(max_length=30)),
                ('rol', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idEmpUsuario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
