# Generated by Django 5.2.3 on 2025-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='nombreCategoria', max_length=25)),
                ('descripcioncategoria', models.CharField(blank=True, db_column='descripcionCategoria', max_length=100, null=True)),
                ('estadocategoria', models.BooleanField(db_column='estadoCategoria', default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('estadocliente', models.BooleanField(db_column='estadoCliente', default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalledevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidaddevuelta', models.IntegerField(db_column='cantidadDevuelta')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
                'db_table': 'detalledevolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Producción',
                'verbose_name_plural': 'Detalles de Producción',
                'db_table': 'detalleproduccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadventa', models.IntegerField(blank=True, db_column='cantidadVenta', null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('iddevolucion', models.AutoField(db_column='idDevolucion', primary_key=True, serialize=False)),
                ('fechadevolucion', models.DateField(blank=True, db_column='fechaDevolucion', null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('rolempleado', models.CharField(blank=True, db_column='rolEmpleado', max_length=30, null=True)),
                ('fechacontratacion', models.DateTimeField(blank=True, db_column='fechaContratacion', null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('estadoempleado', models.BooleanField(db_column='estadoEmpleado', default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('primernombre', models.CharField(db_column='primerNombre', max_length=15)),
                ('segundonombre', models.CharField(blank=True, db_column='segundoNombre', max_length=15, null=True)),
                ('primerapellido', models.CharField(db_column='primerApellido', max_length=15)),
                ('segundoapellido', models.CharField(blank=True, db_column='segundoApellido', max_length=15, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('estadopersona', models.BooleanField(db_column='estadoPersona', default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=30)),
                ('descripcionproducto', models.CharField(blank=True, db_column='descripcionProducto', max_length=70, null=True)),
                ('existenciaproducto', models.IntegerField(db_column='existenciaProducto')),
                ('imagenproductoruta', models.CharField(blank=True, db_column='imagenProductoRuta', max_length=250, null=True)),
                ('precioproducto', models.DecimalField(blank=True, db_column='precioProducto', decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('existenciaminima', models.IntegerField(blank=True, db_column='existenciaMinima', default=5, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productosproduccion',
            fields=[
                ('idproduccion', models.AutoField(db_column='idProduccion', primary_key=True, serialize=False)),
                ('fechaentrada', models.DateField(db_column='fechaEntrada')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estadoregistro', models.BooleanField(db_column='EstadoRegistro', default=True)),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'productosproduccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreubicacion', models.CharField(db_column='nombreUbicacion', max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=15, unique=True)),
                ('passusuario', models.CharField(db_column='passUsuario', max_length=64)),
                ('rol', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField(blank=True, db_column='fechaVenta', null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('REALIZADA', 'Realizada'), ('ANULADA', 'Anulada')], default='REALIZADA', max_length=9)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
