# Generated by Django 5.2.3 on 2025-07-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetalleVenta',
        ),
    ]
