# Generated by Django 5.2.3 on 2025-07-02 03:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_data', '0002_alter_detalleventa_options_alter_detalleventa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('inventario_general', 'Inventario General'), ('produccion', 'Producción'), ('reabastecimientos', 'Reabastecimientos a Sucursal'), ('ventas', 'Ventas'), ('devoluciones', 'Devoluciones'), ('clientes', 'Clientes'), ('usuarios_empleados', 'Usuarios y Empleados'), ('productos_categoria', 'Productos por Categoría'), ('auditoria_sistema', 'Actividad del Sistema')], max_length=50)),
                ('formato_exportacion', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('view', 'Vista en Pantalla')], max_length=10)),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_registros', models.IntegerField(default=0)),
                ('tiempo_generacion', models.FloatField(default=0.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='core_data.usuario')),
            ],
            options={
                'verbose_name': 'Log de Reporte',
                'verbose_name_plural': 'Logs de Reportes',
                'db_table': 'report_log',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('VIEW', 'Ver')], max_length=20)),
                ('modulo', models.CharField(choices=[('inventario', 'Inventario'), ('produccion', 'Producción'), ('ventas', 'Ventas'), ('devoluciones', 'Devoluciones'), ('clientes', 'Clientes'), ('usuarios', 'Usuarios'), ('reportes', 'Reportes'), ('sistema', 'Sistema')], max_length=20)),
                ('descripcion', models.TextField()),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('fecha_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_data.usuario')),
            ],
            options={
                'verbose_name': 'Actividad del Sistema',
                'verbose_name_plural': 'Actividades del Sistema',
                'db_table': 'system_activity',
                'ordering': ['-fecha_actividad'],
            },
        ),
    ]
