# Generated by Django 5.2.3 on 2025-07-01 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe tener 13 dígitos seguidos de una letra', regex='^[0-9]{13}[A-Za-z]$')], verbose_name='Cédula')),
                ('primer_nombre', models.CharField(db_column='primerNombre', max_length=15, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, db_column='segundoNombre', max_length=15, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(db_column='primerApellido', max_length=15, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, db_column='segundoApellido', max_length=15, null=True, verbose_name='Segundo Apellido')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('estado', models.BooleanField(db_column='estadoPersona', default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='idCliente', primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('correo', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Correo Electrónico')),
                ('estado', models.BooleanField(db_column='estadoCliente', default=True, verbose_name='Estado')),
                ('persona', models.ForeignKey(db_column='idPersonaCliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
    ]
